# Generated by Django 5.2.15 on 2026-07-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_purchase',
        ),
    ]
