# Generated by Django 6.0.6 on 2026-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BRANCH_MGR', 'Branch Manager'), ('MARKETING', 'Marketing Manager'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
