# Generated by Django 6.0.6 on 2026-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('BULK_DELETE', 'Bulk Deleted'), ('BULK_UPDATE', 'Bulk Updated'), ('LOGIN', 'Logged In')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_42f1fb_idx'), models.Index(fields=['entity_type', '-created_at'], name='activity_lo_entity__cab177_idx'), models.Index(fields=['user_id', '-created_at'], name='activity_lo_user_id_04b3d2_idx')],
            },
        ),
    ]
