# Generated by Django 6.0.6 on 2026-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccInvMast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slno', models.BigIntegerField()),
                ('invdate', models.DateField(blank=True, null=True)),
                ('customerid', models.CharField(blank=True, max_length=30, null=True)),
                ('nettotal', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_invmast_sync',
                'ordering': ['-invdate', '-slno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(blank=True, max_length=60, null=True)),
                ('exregnodate', models.CharField(blank=True, max_length=30, null=True)),
                ('super_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone2', models.CharField(blank=True, max_length=60, null=True)),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_master_sync',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Misel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'misel_sync',
                'managed': False,
            },
        ),
    ]
