# Generated by Django 6.0.6 on 2026-09-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synctool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misel',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
